version: v1.0.0

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://127.0.0.1:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:8080/
  allowed_return_urls:
    - http://127.0.0.1:8080

  methods:
    password:
      enabled: true
    
  flows:
    login:
      ui_url: http://127.0.0.1:8080/login
      lifespan: 10m
    registration:
      ui_url: http://127.0.0.1:8080/registration
      lifespan: 10m
    settings:
      ui_url: http://127.0.0.1:8080/settings
      lifespan: 10m
    verification:
      ui_url: http://127.0.0.1:8080/verification
      lifespan: 10m
    recovery:
      ui_url: http://127.0.0.1:8080/recovery
      lifespan: 10m

log:
  level: debug
  format: text

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json 
