version: v0.13.0

serve:
  public:
    # base_url: http://127.0.0.1:4433/
    base_url: http://127.0.0.1:8000/kratos
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:8000/welcome
  allowed_return_urls:
    - http://127.0.0.1:8000
    - http://127.0.0.1:8000/selfservice
    - http://localhost:19006/Callback
    - exp://localhost:8081/--/Callback

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:8000/error

    settings:
      ui_url: http://127.0.0.1:8000/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      ui_url: http://127.0.0.1:8000/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:8000/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:8000/welcome

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:8000/selfservice/login

    login:
      # ui_url: http://127.0.0.1:8000/login
      ui_url: http://127.0.0.1:8000/selfservice/login
      lifespan: 10m

    registration:
      lifespan: 10m
      # ui_url: http://127.0.0.1:8000/registration
      ui_url: http://127.0.0.1:8000/selfservice/registration
      after:
        oidc:
          hooks:
            - hook: session
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

hashers:
  argon2:
    parallelism: 1
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json 

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

feature_flags:
  use_continue_with_transitions: true
