services:
  traefik:
    image: traefik
    command:
      - '--api.dashboard=true'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:8000'
    ports:
      - '8000:8000'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  whoami-public:
    image: traefik/whoami
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami-public.entrypoints=web'
      - 'traefik.http.routers.whoami-public.rule=PathPrefix(`/public`)'
      - 'traefik.http.services.whoami-public.loadbalancer.server.port=80'
      - 'traefik.http.routers.whoami-public.middlewares=strip-public'
      - 'traefik.http.middlewares.strip-public.stripprefix.prefixes=/public'
  whoami-private:
    image: traefik/whoami
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami-private.entrypoints=web'
      - 'traefik.http.routers.whoami-private.rule=PathPrefix(`/private`)'
      - 'traefik.http.routers.whoami-private.middlewares=strip-private'
      - 'traefik.http.middlewares.strip-private.stripprefix.prefixes=/private'
  kratos-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    volumes:
      - kratos-data:/var/lib/postgresql/data
    restart: unless-stopped
  kratos-migrate:
    image: oryd/kratos:v1.3.1
    environment:
      - DSN=postgres://kratos:secret@kratos-data:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./config/kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    depends_on:
      - kratos-db
