services:
  traefik:
    image: traefik
    command:
      - '--log.level=DEBUG'
      - '--api.dashboard=true'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--accesslog=true'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.http.middlewares.oathkeeper.forwardauth.address=http://oathkeeper:4456/decisions'
      - 'traefik.http.middlewares.oathkeeper.forwardauth.authResponseHeaders=X-ID-Token,X-User-ID,X-User,,Authorization'
    networks:
      - intranet
  oathkeeper:
    image: oryd/oathkeeper:v0.40.9
    command: serve -c /etc/config/oathkeeper/oathkeeper.yml
    environment:
      - LOG_LEVEL=debug
    volumes:
      - type: bind
        source: ./config/oathkeeper
        target: /etc/config/oathkeeper
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.oathkeeper.entrypoints=web'
      - 'traefik.http.routers.oathkeeper.rule=Host(`oathkeeper.intranet`)'
      - 'traefik.http.routers.oathkeeper.service=oathkeeper'
      - 'traefik.http.services.oathkeeper.loadbalancer.server.port=4456'
    restart: unless-stopped
    networks:
      - intranet
  kratos-migrate:
    image: oryd/kratos:v1.3.1
    environment:
      - DSN=postgres://kratos:secret@kratos-db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: volume
        source: kratos-db
        target: /var/lib/postgresql/data
      - type: bind
        source: ./config/kratos
        target: /etc/config/kratos
    command: migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet
  kratos-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - intranet
  prometheus:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prometheus.entrypoints=web'
      - 'traefik.http.routers.prometheus.rule=Host(`prometheus.intranet`) && PathPrefix(`/api/v1/`)'
      - 'traefik.http.routers.prometheus.service=prometheus'
      - 'traefik.http.services.prometheus.loadbalancer.server.port=8000'

      - 'traefik.http.routers.prometheus.middlewares=oathkeeper'

      - 'traefik.http.middlewares.oathkeeper.forwardauth.address=http://oathkeeper:4456/decisions'
      - 'traefik.http.middlewares.oathkeeper.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.oathkeeper.forwardauth.authResponseHeaders=X-User-ID,X-Forwarded-User,X-Session-Token,Authorization'
      - 'traefik.http.middlewares.oathkeeper.forwardauth.authRequestHeaders=Cookie,Authorization'
    networks:
      - intranet
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.3.1
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
      - PORT=4435
      - SECURITY_MODE=
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.kratos-ui.entrypoints=web'
      - 'traefik.http.routers.kratos-ui.rule=Host(`kratos-ui.intranet`)'
      - 'traefik.http.routers.kratos-ui.service=kratos-ui'
      - 'traefik.http.services.kratos-ui.loadbalancer.server.port=4433'
    networks:
      - intranet
    restart: on-failure
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.3.1
    restart: unless-stopped
    environment:
      - SERVE_PUBLIC_BASE_URL=http://kratos:4455/.ory/kratos/public
      - DSN=postgres://kratos:secret@kratos-db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./config/kratos
        target: /etc/config/kratos
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.kratos.entrypoints=web'
      - 'traefik.http.routers.kratos.rule=Host(`kratos.intranet`)'
      - 'traefik.http.routers.kratos.service=kratos'
      - 'traefik.http.services.kratos.loadbalancer.server.port=4455'

      - 'traefik.http.routers.kratos-admin.entrypoints=web'
      - 'traefik.http.routers.kratos-admin.rule=Host(`kratos-admin.intranet`)'
      - 'traefik.http.routers.kratos-admin.service=kratos-admin'
      - 'traefik.http.services.kratos-admin.loadbalancer.server.port=4456'
    networks:
      - intranet
  whoami-private:
    image: traefik/whoami
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami-private.entrypoints=web'
      - 'traefik.http.routers.whoami-private.rule=Host(`whoami-private.intranet`)'
      - 'traefik.http.routers.whoami-private.service=whoami-private'
      - 'traefik.http.routers.whoami-private.middlewares=oathkeeper'
      - 'traefik.http.services.whoami-private.loadbalancer.server.port=80'
  whoami-public:
    image: traefik/whoami
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami-public.entrypoints=web'
      - 'traefik.http.routers.whoami-public.rule=Host(`whoami-public.intranet`)'
      - 'traefik.http.routers.whoami-public.service=whoami-public'
      - 'traefik.http.routers.whoami-public.middlewares=redirect-to-selfservice'
      - 'traefik.http.services.whoami-public.loadbalancer.server.port=80'
      - 'traefik.http.middlewares.redirect-to-selfservice.redirectregex.regex=^.*$'
      - 'traefik.http.middlewares.redirect-to-selfservice.redirectregex.replacement=http://kratos-ui.intranet'
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    networks:
      - intranet

networks:
  intranet:

volumes:
  kratos-db: 
