services:
  traefik:
    image: traefik
    command:
      - '--api.dashboard=true'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:8000'
    ports:
      - '8000:8000'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  oathkeeper:
    image: oryd/oathkeeper:v0.40.9
    volumes:
      - ./config/oathkeeper:/etc/config/oathkeeper
    command: serve -c /etc/config/oathkeeper/oathkeeper.yml
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.oathkeeper.entrypoints=web'
      - 'traefik.http.routers.oathkeeper.rule=PathPrefix(`/oathkeeper`)'
      - 'traefik.http.services.oathkeeper.loadbalancer.server.port=4456'
    restart: unless-stopped
  whoami-public:
    image: traefik/whoami
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami-public.entrypoints=web'
      - 'traefik.http.routers.whoami-public.rule=PathPrefix(`/public`)'
      - 'traefik.http.services.whoami-public.loadbalancer.server.port=80'
      - 'traefik.http.routers.whoami-public.middlewares=strip-public'
      - 'traefik.http.middlewares.strip-public.stripprefix.prefixes=/public'
  whoami-private:
    image: traefik/whoami
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami-private.entrypoints=web'
      - 'traefik.http.routers.whoami-private.rule=PathPrefix(`/private`)'
      - 'traefik.http.routers.whoami-private.middlewares=strip-private'
      - 'traefik.http.middlewares.strip-private.stripprefix.prefixes=/private'

      - 'traefik.http.middlewares.oathkeeper.forwardauth.address=http://oathkeeper:4456/decisions'
      - 'traefik.http.middlewares.oathkeeper.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.oathkeeper.forwardauth.authResponseHeaders=X-Session-ID,X-User'

      - 'traefik.http.routers.whoami-private.middlewares=oathkeeper@docker'
  prometheus:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.prometheus.entrypoints=web'
      - 'traefik.http.routers.prometheus.rule=PathPrefix(`/api/v1/`)'
      - 'traefik.http.routers.prometheus.service=prometheus'
      - 'traefik.http.services.prometheus.loadbalancer.server.port=80'
      - 'traefik.http.routers.prometheus.middlewares=strip-path'
      - 'traefik.http.middlewares.strip-path.stripprefix.prefixes=/api/v1/'

      - 'traefik.http.middlewares.oathkeeper.forwardauth.address=http://oathkeeper:4456/decisions'
      - 'traefik.http.middlewares.oathkeeper.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.oathkeeper.forwardauth.authResponseHeaders=X-Session-ID,X-User'

      - 'traefik.http.routers.whoami-private.middlewares=oathkeeper@docker'
  kratos-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    volumes:
      - kratos-data:/var/lib/postgresql/data
    restart: unless-stopped
  kratos-migrate:
    image: oryd/kratos:v1.3.1
    environment:
      - DSN=postgres://kratos:secret@kratos-db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./config/kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: unless-stopped
    depends_on:
      - kratos-db
  kratos:
    image: oryd/kratos:v1.3.1
    environment:
      - DSN=postgres://kratos:secret@kratos-db:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./config/kratos:/etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.kratos.entrypoints=web'
      - 'traefik.http.routers.kratos.rule=PathPrefix(`/kratos`)'
      - 'traefik.http.services.kratos.loadbalancer.server.port=4433'
      - 'traefik.http.routers.kratos.middlewares=strip-kratos'
      - 'traefik.http.middlewares.strip-kratos.stripprefix.prefixes=/kratos'
    restart: unless-stopped
    depends_on:
      - kratos-migrate
  kratos-ui:
    image: oryd/kratos-selfservice-ui-node:v1.3.1
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://localhost:8000/kratos/
      - PORT=4435
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.kratos-ui.entrypoints=web'
      - 'traefik.http.routers.kratos-ui.rule=PathPrefix(`/selfservice/`)'
      - 'traefik.http.services.kratos-ui.loadbalancer.server.port=4435'
      - 'traefik.http.routers.kratos-ui.middlewares=strip-selfservice'
      - 'traefik.http.middlewares.strip-selfservice.stripprefix.prefixes=/selfservice'
    restart: unless-stopped
    depends_on:
      - kratos
volumes:
  kratos-data:
