- id: prometheus
  upstream:
    url: http://prometheus:80
    preserve_host: true
  match:
    url: http://localhost:8000/api/v1/**
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token

- id: whoami-private
  upstream:
    url: http://whoami-private:80
    preserve_host: true
  match:
    url: http://localhost:8000/private
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
