- id: whoami-private
  upstream:
    preserve_host: true
    url: http://whoami-private
  match:
    url: http://localhost:8000/private
    methods:
      - GET
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: noop
