- id: prometheus
  upstream:
    url: http://prometheus:80
    preserve_host: true
  match:
    url: http://localhost:8000/api/v1/**
    methods:
      - GET
      - POST
      - DELETE
      - PUT
      - PATCH
  authenticators:
    - handler: cookie_session
  authorizer:
    - handler: allow
  mutators:
    - handler: id_token

- id: whoami-private
  upstream:
    url: http://whoami-private:80
    preserve_host: true
  match:
    url: http://localhost:8000/private
    methods:
      - GET
      - POST
  authenticators:
    - handler: cookie_session
  authorizer:
    - handler: allow
  mutators:
    - handler: noop
  errors:
    - handler: redirect
