serve:
  proxy:
    cors:
      enabled: true
    allowed_origins:
      - '*'
    allowed_methods:
      - POST
      - GET
      - PUT
      - DELETE
      - PATCH
    allowed_headers:
      - Authorization
      - Cookie
      - Content-Type
    exposed_headers:
      - Content-Type
      - Set-Cookie
    allow_credentials: true
    debug: true

access_rules:
  matching_strategy: glob
  repositories:
    - file:///etc/config/oathkeeper/access-rules.yml
