serve:
  proxy:
    cors:
      enabled: true
      allowed_origins:
        - '*'
      allowed_methods:
        - POST
        - GET
        - PUT
        - DELETE
        - PATCH
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie
      allow_credentials: true
      debug: true

access_rules:
  matching_strategy: glob
  repositories:
    - file:///etc/config/oathkeeper/access-rules.yml

authenticators:
  anonymous:
    enabled: true
    config:
      subject: guest
  cookie_session:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
      forward_http_headers:
        - Cookie
      only:
        - ory_kratos_session
  noop:
    enabled: true

authorizers:
  allow:
    enabled: true
  deny:
    enabled: true

mutators:
  noop:
    enabled: true

errors:
  fallback:
    - redirect
  handlers:
    redirect:
      enabled: true
      config:
        to: http://localhost:8000/selfservice/login
        when:
          - error:
            - unauthorized
            - forbidden
            request:
              header:
                accept:
                  - text/html
    json:
      enabled: true
      config:
        verbose: true
